import * as NodeFS from "node:fs/promises";
import * as NodePath from "node:path";
const __dirname = NodePath.dirname(new URL(import.meta.url).pathname);
const banner = `/* Automatically generated by ${NodePath.basename(
  new URL(import.meta.url).pathname,
)}. Do not modify by hand. */`;

const indexScript = [banner];

for (const i of Array.from(new Array(26), (_, i) => i)) {
  const pkg = String.fromCharCode(i + "a".charCodeAt(0));
  const page = pkg + pkg;
  const pkgName = `@internals/${pkg}`;
  const script = `${banner}
import { ${pkg} } from "${pkgName}";

console.log("${pkgName}", ${pkg});
`;
  const pkgMainScript = `${banner}
export const ${pkg} = "${pkg}";
`;

  await writeFile(
    NodePath.resolve(__dirname, `./src/pages/${page}.js`),
    script,
  );

  await writeFile(
    NodePath.resolve(__dirname, `./node_modules/${pkgName}/index.js`),
    pkgMainScript,
  );

  indexScript.push(`import "./pages/${page}";`);
}

await writeFile(
  NodePath.resolve(__dirname, "./src/index.js"),
  indexScript.join("\n"),
);

/**
 *
 * @param {string} path
 * @param {string} content
 */
async function writeFile(path, content) {
  const dir = NodePath.dirname(path);
  await NodeFS.mkdir(dir, { recursive: true, mode: 0o755 });
  await NodeFS.writeFile(path, content, { mode: 0o644 });
}
